version: "3.4"
networks: 
  app:
volumes:
  geth_data:
services:
  geth:
    image: ethereum/client-go:stable
    ports:
      - 30303:30303
      - 8545:8545
      - 8546:8545
      - 8547:8545
    volumes:
      - geth_data:/root/.ethereum
    networks:
      - app
